name: Deploy Theme to SpinupWP

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v3

            - name: Install SSH Key
              uses: webfactory/ssh-agent@v0.8.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Add known hosts
              run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

            - name: Sync Theme to SpinupWP
              run: |
                  rsync -avz --delete \
                  --exclude '.git/' \
                  --exclude '.github/' \
                  --exclude 'node_modules/' \
                  ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET_DIR }}
